"""Add soft delete to courses

Revision ID: 4ad264799b80
Revises: 9bdaf3389a20
Create Date: 2024-12-14 00:43:25.376617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ad264799b80'
down_revision: Union[str, None] = '9bdaf3389a20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('courses', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'deleted_at')
    op.drop_column('courses', 'is_deleted')
    # ### end Alembic commands ###
